//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nTierDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class aspnet_Employees
    {
        public aspnet_Employees()
        {
            this.tbl_ORDER = new HashSet<tbl_ORDER>();
            this.tbl_ORDER1 = new HashSet<tbl_ORDER>();
        }
    
        public System.Guid UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<System.DateTime> HireDate { get; set; }
        public string ResidenceAddress { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> ResidenceTel { get; set; }
        public Nullable<int> OfficeTel { get; set; }
        public Nullable<int> MobileNo { get; set; }
        public string Photo { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
    
        public virtual aspnet_Employees aspnet_Employees1 { get; set; }
        public virtual aspnet_Employees aspnet_Employees2 { get; set; }
        public virtual tbl_CITY tbl_CITY { get; set; }
        public virtual aspnet_Users aspnet_Users { get; set; }
        public virtual ICollection<tbl_ORDER> tbl_ORDER { get; set; }
        public virtual ICollection<tbl_ORDER> tbl_ORDER1 { get; set; }
    }
}
