//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nTierDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_COUNTRY
    {
        public tbl_COUNTRY()
        {
            this.tbl_CITY = new HashSet<tbl_CITY>();
        }
    
        public int CountryId { get; set; }
        public string Country { get; set; }
    
        public virtual ICollection<tbl_CITY> tbl_CITY { get; set; }
    }
}
