//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nTierDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CATEGORY
    {
        public tbl_CATEGORY()
        {
            this.tbl_PRODUCTS = new HashSet<tbl_PRODUCTS>();
        }
    
        public int CategoryId { get; set; }
        public int BranchId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<tbl_PRODUCTS> tbl_PRODUCTS { get; set; }
        public virtual tbl_BRANCH tbl_BRANCH { get; set; }
    }
}
