//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nTierDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CUSTOMER
    {
        public tbl_CUSTOMER()
        {
            this.tbl_ORDER = new HashSet<tbl_ORDER>();
        }
    
        public int CustomerID { get; set; }
        public int CityId { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Phone3 { get; set; }
    
        public virtual ICollection<tbl_ORDER> tbl_ORDER { get; set; }
    }
}
