//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nTierDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PRODUCTS
    {
        public tbl_PRODUCTS()
        {
            this.tbl_ORDER_DETAIL = new HashSet<tbl_ORDER_DETAIL>();
        }
    
        public int ProductId { get; set; }
        public string Name { get; set; }
        public int CategoryId { get; set; }
        public string Description { get; set; }
        public double Price { get; set; }
        public string UnitSize { get; set; }
        public string Picture { get; set; }
        public bool IsEnable { get; set; }
    
        public virtual tbl_CATEGORY tbl_CATEGORY { get; set; }
        public virtual ICollection<tbl_ORDER_DETAIL> tbl_ORDER_DETAIL { get; set; }
    }
}
