//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nTierDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AREAS
    {
        public tbl_AREAS()
        {
            this.tbl_BRANCH = new HashSet<tbl_BRANCH>();
        }
    
        public int AeraId { get; set; }
        public int CityId { get; set; }
        public string Area { get; set; }
    
        public virtual tbl_CITY tbl_CITY { get; set; }
        public virtual ICollection<tbl_BRANCH> tbl_BRANCH { get; set; }
    }
}
