//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nTierDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ORDER_DETAIL
    {
        public long OrderDetailId { get; set; }
        public int OrderId { get; set; }
        public int ProductId { get; set; }
        public int ProductUnitSize { get; set; }
        public double TaxAmount { get; set; }
        public int Quantity { get; set; }
        public int Discount { get; set; }
    
        public virtual tbl_PRODUCTS tbl_PRODUCTS { get; set; }
        public virtual tbl_ORDER tbl_ORDER { get; set; }
    }
}
